// src/utils/currencies.ts
export const CURRENCY_NAMES: Record<string, string> = {
  // Devises populaires
  EUR: 'Euro',
  USD: 'Dollar américain',
  MGA: 'Ariary malgache',
  GBP: 'Livre sterling',
  JPY: 'Yen japonais',
  CAD: 'Dollar canadien',
  CHF: 'Franc suisse',
  AUD: 'Dollar australien',
  CNY: 'Yuan chinois',
  HKD: 'Dollar de Hong Kong',
  SGD: 'Dollar de Singapour',
  NZD: 'Dollar néo-zélandais',

  // Europe
  SEK: 'Couronne suédoise',
  NOK: 'Couronne norvégienne',
  DKK: 'Couronne danoise',
  CZK: 'Couronne tchèque',
  HUF: 'Forint hongrois',
  PLN: 'Zloty polonais',
  RON: 'Leu roumain',
  BGN: 'Lev bulgare',
  HRK: 'Kuna croate',
  RSD: 'Dinar serbe',
  ISK: 'Couronne islandaise',
  TRY: 'Livre turque',
  RUB: 'Rouble russe',
  UAH: 'Hryvnia ukrainienne',

  // Amériques
  BRL: 'Real brésilien',
  MXN: 'Peso mexicain',
  ARS: 'Peso argentin',
  CLP: 'Peso chilien',
  COP: 'Peso colombien',
  PEN: 'Sol péruvien',
  UYU: 'Peso uruguayen',
  BOB: 'Boliviano bolivien',
  PYG: 'Guaraní paraguayen',
  VES: 'Bolívar vénézuélien',
  CRC: 'Colón costaricien',
  GTQ: 'Quetzal guatémaltèque',
  HNL: 'Lempira hondurien',
  NIO: 'Córdoba nicaraguayen',
  DOP: 'Peso dominicain',
  TTD: 'Dollar de Trinité-et-Tobago',
  JMD: 'Dollar jamaïcain',
  BBD: 'Dollar barbadien',
  BSD: 'Dollar bahamien',
  BZD: 'Dollar bélizien',

  // Asie
  INR: 'Roupie indienne',
  KRW: 'Won sud-coréen',
  IDR: 'Roupiah indonésienne',
  MYR: 'Ringgit malaisien',
  THB: 'Baht thaïlandais',
  PHP: 'Peso philippin',
  VND: 'Dông vietnamien',
  BDT: 'Taka bangladais',
  PKR: 'Roupie pakistanaise',
  LKR: 'Roupie sri-lankaise',
  NPR: 'Roupie népalaise',
  MMK: 'Kyat birman',
  KHR: 'Riel cambodgien',
  LAK: 'Kip laotien',
  MNT: 'Tögrög mongol',
  TWD: 'Dollar taiwanais',
  KZT: 'Tenge kazakh',
  UZS: 'Sum ouzbek',
  AZN: 'Manat azerbaïdjanais',
  GEL: 'Lari géorgien',
  AMD: 'Dram arménien',

  // Moyen-Orient
  AED: 'Dirham des Émirats',
  SAR: 'Riyal saoudien',
  QAR: 'Riyal qatari',
  KWD: 'Dinar koweïtien',
  BHD: 'Dinar bahreïni',
  OMR: 'Rial omanais',
  ILS: 'Shekel israélien',
  JOD: 'Dinar jordanien',
  LBP: 'Livre libanaise',
  IRR: 'Rial iranien',
  IQD: 'Dinar irakien',

  // Afrique
  ZAR: 'Rand sud-africain',
  NGN: 'Naira nigérian',
  EGP: 'Livre égyptienne',
  GHS: 'Cédi ghanéen',
  KES: 'Shilling kényan',
  TZS: 'Shilling tanzanien',
  UGX: 'Shilling ougandais',
  ETB: 'Birr éthiopien',
  MAD: 'Dirham marocain',
  TND: 'Dinar tunisien',
  DZD: 'Dinar algérien',
  XOF: 'Franc CFA Ouest',
  XAF: 'Franc CFA Centre',
  AOA: 'Kwanza angolais',
  MZN: 'Metical mozambicain',
  ZMW: 'Kwacha zambien',
  BWP: 'Pula botswanais',
  RWF: 'Franc rwandais',
  MUR: 'Roupie mauricienne',
  SCR: 'Roupie seychelloise',
  GMD: 'Dalasi gambien',
  SLL: 'Leone sierra-léonais',
  LRD: 'Dollar libérien',
  CDF: 'Franc congolais',
  SDG: 'Livre soudanaise',
  SOS: 'Shilling somalien',
  DJF: 'Franc djiboutien',
  ERN: 'Nakfa érythréen',
  MWK: 'Kwacha malawien',

  // Océanie
  FJD: 'Dollar fidjien',
  PGK: 'Kina papou',
  WST: 'Tālā samoan',
  TOP: 'Paʻanga tongan',
  VUV: 'Vatu vanuatais',
  SBD: 'Dollar des Salomon',

  // Autres / Crypto / Spéciaux
  XCD: 'Dollar des Caraïbes',
  XPF: 'Franc CFP',
  AWG: 'Florin arubais',
  ANG: 'Florin antillais',
  BMD: 'Dollar bermudien',
  KYD: 'Dollar des Caïmans',
  GYD: 'Dollar guyanais',
  SRD: 'Dollar surinamais',
  HTG: 'Gourde haïtienne',
  CUP: 'Peso cubain',
  MOP: 'Pataca macanais',
  BND: 'Dollar de Brunei',
  BTN: 'Ngultrum bouthanais',
  MVR: 'Rufiyaa maldivienne',
  AFN: 'Afghani afghan',
  TJS: 'Somoni tadjik',
  TMT: 'Manat turkmène',
  KGS: 'Som kirghiz',
  MKD: 'Denar macédonien',
  ALL: 'Lek albanais',
  BAM: 'Mark bosnien',
  MDL: 'Leu moldave',
  BYN: 'Rouble biélorusse',
  GNF: 'Franc guinéen',
  XDR: 'Droits de tirage spéciaux (FMI)',
};

/**
 * Retourne le nom complet d'une devise, ou le code si inconnu.
 */
export const getCurrencyName = (code: string): string =>
  CURRENCY_NAMES[code] ?? code;

