export const CURRENCY_REGIONS: Record<string, string[]> = {
  // Populaires
  EUR: ['Populaires', 'Europe'],
  USD: ['Populaires', 'Amériques'],
  MGA: ['Populaires', 'Afrique'],
  GBP: ['Populaires', 'Europe'],
  JPY: ['Populaires', 'Asie'],
  CAD: ['Populaires', 'Amériques'],
  CHF: ['Populaires', 'Europe'],
  AUD: ['Populaires', 'Océanie'],
  CNY: ['Populaires', 'Asie'],
  HKD: ['Populaires', 'Asie'],
  SGD: ['Populaires', 'Asie'],
  NZD: ['Populaires', 'Océanie'],

  // Europe
  SEK: ['Europe'],
  NOK: ['Europe'],
  DKK: ['Europe'],
  CZK: ['Europe'],
  HUF: ['Europe'],
  PLN: ['Europe'],
  RON: ['Europe'],
  BGN: ['Europe'],
  HRK: ['Europe'],
  RSD: ['Europe'],
  ISK: ['Europe'],
  TRY: ['Europe'],
  RUB: ['Europe'],
  UAH: ['Europe'],

  // Amériques
  BRL: ['Amériques'],
  MXN: ['Amériques'],
  ARS: ['Amériques'],
  CLP: ['Amériques'],
  COP: ['Amériques'],
  PEN: ['Amériques'],
  UYU: ['Amériques'],
  BOB: ['Amériques'],
  PYG: ['Amériques'],
  VES: ['Amériques'],
  CRC: ['Amériques'],
  GTQ: ['Amériques'],
  HNL: ['Amériques'],
  NIO: ['Amériques'],
  DOP: ['Amériques'],
  TTD: ['Amériques'],
  JMD: ['Amériques'],
  BBD: ['Amériques'],
  BSD: ['Amériques'],
  BZD: ['Amériques'],

  // Asie
  INR: ['Asie'],
  KRW: ['Asie'],
  IDR: ['Asie'],
  MYR: ['Asie'],
  THB: ['Asie'],
  PHP: ['Asie'],
  VND: ['Asie'],
  BDT: ['Asie'],
  PKR: ['Asie'],
  LKR: ['Asie'],
  NPR: ['Asie'],
  MMK: ['Asie'],
  KHR: ['Asie'],
  LAK: ['Asie'],
  MNT: ['Asie'],
  TWD: ['Asie'],
  KZT: ['Asie'],
  UZS: ['Asie'],
  AZN: ['Asie'],
  GEL: ['Asie'],
  AMD: ['Asie'],

  // Moyen-Orient
  AED: ['Moyen-Orient'],
  SAR: ['Moyen-Orient'],
  QAR: ['Moyen-Orient'],
  KWD: ['Moyen-Orient'],
  BHD: ['Moyen-Orient'],
  OMR: ['Moyen-Orient'],
  ILS: ['Moyen-Orient'],
  JOD: ['Moyen-Orient'],
  LBP: ['Moyen-Orient'],
  IRR: ['Moyen-Orient'],
  IQD: ['Moyen-Orient'],

  // Afrique
  ZAR: ['Afrique'],
  NGN: ['Afrique'],
  EGP: ['Afrique'],
  GHS: ['Afrique'],
  KES: ['Afrique'],
  TZS: ['Afrique'],
  UGX: ['Afrique'],
  ETB: ['Afrique'],
  MAD: ['Afrique'],
  TND: ['Afrique'],
  DZD: ['Afrique'],
  XOF: ['Afrique'],
  XAF: ['Afrique'],
  AOA: ['Afrique'],
  MZN: ['Afrique'],
  ZMW: ['Afrique'],
  BWP: ['Afrique'],
  RWF: ['Afrique'],
  MUR: ['Afrique'],
  SCR: ['Afrique'],
  GMD: ['Afrique'],
  SLL: ['Afrique'],
  LRD: ['Afrique'],
  CDF: ['Afrique'],
  SDG: ['Afrique'],
  SOS: ['Afrique'],
  DJF: ['Afrique'],
  ERN: ['Afrique'],
  MWK: ['Afrique'],

  // Océanie
  FJD: ['Océanie'],
  PGK: ['Océanie'],
  WST: ['Océanie'],
  TOP: ['Océanie'],
  VUV: ['Océanie'],
  SBD: ['Océanie'],

  // Autres
  XCD: ['Amériques'],
  XPF: ['Océanie'],
  AWG: ['Amériques'],
  ANG: ['Amériques'],
  BMD: ['Amériques'],
  KYD: ['Amériques'],
  GYD: ['Amériques'],
  SRD: ['Amériques'],
  HTG: ['Amériques'],
  CUP: ['Amériques'],
  MOP: ['Asie'],
  BND: ['Asie'],
  BTN: ['Asie'],
  MVR: ['Asie'],
  AFN: ['Asie'],
  TJS: ['Asie'],
  TMT: ['Asie'],
  KGS: ['Asie'],
  MKD: ['Europe'],
  ALL: ['Europe'],
  BAM: ['Europe'],
  MDL: ['Europe'],
  BYN: ['Europe'],
  GNF: ['Afrique'],
  XDR: ['Autres'],
};

export const getCurrencyRegions = (code: string): string[] =>
  CURRENCY_REGIONS[code] ?? [];